spring:
  application:
    name: order
  servlet:
    multipart:
      enabled: true

eureka:
  instance:
    hostname: order1
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
server:
  port: 8001
bus:
  test: cccc
